import { ArrowLeft, ArrowUpRight, BadgeCheck, Building2, CheckCircle2, FileCheck2, ShieldCheck, Sparkles, Users } from 'lucide-react';
import { Link } from '@/components/HashLink';

export default function OrgGuardPremium() {
  return <div className="modern-page orgguard-page"><div className="container">
    <Link className="back-link" href="#/"><ArrowLeft size={15}/> Back to GUARDIAN</Link>
    <div className="orgguard-hero-modern"><div><div className="section-kicker light">OrgGuard · recommendation layer</div><h1>Invest with confidence.<br /><em>Protect every asset.</em></h1><p>Green status is not a shortcut. It is a documented signal of transparency, consistency, and a record ready for the next level of scrutiny.</p></div><div className="orgguard-seal"><ShieldCheck size={31}/><span>TRUST<br />LAYER</span></div></div>
    <div className="orgguard-metrics"><div><strong>4</strong><span>risk tiers<br />in one language</span></div><div><strong>2×</strong><span>review layer<br />for every record</span></div><div><strong>24/7</strong><span>on-demand<br />verification access</span></div></div>
    <section className="orgguard-content"><div className="section-kicker">Verified recommendations</div><div className="recommendation-grid-modern"><Recommendation icon={<Users/>} title="Daw Thazin Oo" type="Employee" status="Verified & highly recommended" copy="Eight-plus years in operations management with a consistently clean disciplinary record." /><Recommendation icon={<Building2/>} title="Prime Build Development Co., Ltd." type="Corporate" status="Fully compliant & investor ready" copy="A transparent construction partner with a strong delivery record and no verified safety violations." /><Recommendation icon={<Sparkles/>} title="Clean Water Initiative Myanmar" type="Organization" status="Highly transparent & donor ready" copy="A mission-led organization with documented governance and clean project evidence." /></div></section>
    <section className="orgguard-operating"><div><div className="section-kicker">The operating model</div><h2>Simple on the surface.<br /><span>Rigorous underneath.</span></h2><p>GUARDIAN gives every stakeholder a shared operating language for evidence-backed decisions.</p></div><div className="operating-steps"><Step n="01" icon={<FileCheck2/>} title="Search" text="Enter a name, ID, license, or organization."/><Step n="02" icon={<BadgeCheck/>} title="Review" text="Open the evidence, legal action, signatures, and entities."/><Step n="03" icon={<CheckCircle2/>} title="Challenge" text="Submit corrections with documented evidence."/></div></section>
    <div className="orgguard-cta"><div><strong>Build your trust layer.</strong><span>Investors, donors, and HR teams all need a clear decision trail.</span></div><Link className="light-button" href="#/pricing">Explore plans <ArrowUpRight size={16}/></Link></div>
  </div></div>;
}
function Recommendation({icon,title,type,status,copy}:{icon:React.ReactNode;title:string;type:string;status:string;copy:string}) { return <article className="recommendation-modern"><div className="recommendation-icon">{icon}</div><span className="recommendation-type">{type}</span><h3>{title}</h3><strong><CheckCircle2 size={14}/> {status}</strong><p>{copy}</p><Link href="#/search" className="text-button">Check more <ArrowUpRight size={14}/></Link></article>; }
function Step({n,icon,title,text}:{n:string;icon:React.ReactNode;title:string;text:string}) { return <div className="operating-step"><span>{n}</span><div>{icon}</div><h3>{title}</h3><p>{text}</p></div>; }
